# Generated by Django 3.2 on 2021-04-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='hash',
            field=models.CharField(default=None, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
