# Generated by Django 3.2 on 2021-04-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
